- name: create file and copy content
  hosts: all
  tasks:
  - name: create file and copy content
    copy:
     dest: "/tmp/test.txt"
     content:
       This is first line
       This is second line
     register: output
  - name: print result
    debug:
     var: output
     
     
