---
- name: test datasource
  hosts: all
  tasks:
   - name: test datasource
     shell:
       echo 'x="{{item}}"'
    with_items:
          - A
     register: output_result
   - name: print result
     debug:
      var: "the result is {{ output_result.stdout }}"
